### ISSUE TITLE
Nail down the architecture of using sub-guides within Foxlight

### ISSUE THREAD

**Issue by cassiemc** [mozilla/mozmaker#30]
I think @gvn's plan to have subguides overwrite styles is good. With this ticket I'd like to make sure we are all on the same page. cc @flukeout @vazquez 

If we want to test this we could start with a smaller subguide for Teach based on @kristinashu's [colour work here](https://github.com/MozillaFoundation/Design/issues/139 ). If the subguide only consisted of colors for now, that's fine, and may in fact even be the only change we ever need to consider. (related but not this... some sites will have different wrappers). cc @hannahkane @simonwex

**Comment by gvn** [comment]
I'm wondering if we should think of sub-guides and templates as the same thing?

Currently the architecture is like this:

**Foxlight** contains all the overarching style definitions and components.

**Foxlight Templates** exist in a separate repository and contain HTML markup for standard layouts as well as any custom styles unique to the individual temples (e.g. a very custom hero module that is only used for 1 template). **Foxlight Templates** includes **Foxlight** as a dependency and overrides where needed.

I could see a case where a sub-guide applies to many templates, in which case, maybe we need to keep them separate from the templates?

Curious to hear everyone's thoughts. 

I do feel strongly about keeping Foxlight relatively small and for our "master" styles rather than put a bunch of edge cases into it. It's totally fine to override Foxlight where necessary in the templates that consume it. This will keep things simple.

**Comment by cassiemc** [comment]
@vazquez @flukeout @simonwex Thoughts?

I think this is important:
> I could see a case where a sub-guide applies to many templates, in which case, maybe we need to keep them separate from the templates?

We very likely will reuse templates across sites/brands that will require minor variations in styles.

@gvn can I assign this to you?

**Comment by gvn** [comment]
Yep, totally

**Comment by gvn** [comment]
I think this is addressed now. @vazquez  and I came up with a way of extending the templates with different sub-themes. Right now they're just palettes being swapped, but we could do other customization in a similar manner...
