### ISSUE TITLE
Change base font size to 10px

### ISSUE THREAD

**Issue by gvn** [mozilla/mozmaker#65]
Right now we have a 16px base font size here, which makes using rems fairly cumbersome. With 10px we can do any pixel->rem math very easily (ie: 10px = 1rem).

I think 16px is a new default in Bootstrap 4. We're using a 10px base in the Science rebuild.

I feel like we should change it here too, which will require refactoring all our rems (multiply them all by 1.6).

Thoughts? @alanmoo @vazquez

**Comment by vazquez** [comment]
Sorry I'm a little confused. Are you suggesting we change our base font size to 10px or 16px?

**Comment by alanmoo** [comment]
I believe he's suggesting we put 
`````
html{
    font-size: 10px;
}
body{
    font-size: 1.6rem;
}
```` 

in this project so that when we use rem elsewhere in a project, it's easier to calculate. It will effectively make us more likely to use rem, which could theoretically be good if we ever decide to dynamically change the font size in a project based on something like screen size.

The only downside I can imagine is if we bring 3rd party components in that happen to use `rem` sizing, but we can always apply CSS to reset the component's font (and this is an imagined issue, not one I've ever actually seen).

I would say a change like this warrants a Major version change, as in the world of CSS it's a breaking change.

**Comment by gvn** [comment]
Actually, what we did on Science is: 

```css
html {
    font-size: 10px;
}

body {
    font-size: 1rem;
}
```

But probably we should change Science instead of Mozmaker, as I'm realizing this is going to cause Bootstrap not to layout properly since it expects body at 1.6rem. Derp...

**Comment by xmatthewx** [comment]
It might be helpful to establish a scale that designers use, something that's visually musical and sensible mathematically. For both type and layout (padding, margin, components).

10, 12, 14, ~~15~~, 16, 20, 24, ~~25~~, 28, 32, ... 48, ~~50~~ ... 

Forgive me if this has been discussed previously. 
cc @kristinashu @sabrinang

**Comment by alanmoo** [comment]
I think that's a bit of a different issue, @xmatthewx.

**Comment by xmatthewx** [comment]
How so? I'm suggesting that we do the math once, in unison, so that we never need to do that math again. In a future project, comps would utilize 3rem instead of 50px for a thumbnail. Grids, components, type, could all be optimized for both users and implementation.

**Comment by gvn** [comment]
I'm gonna close this because we need to stick to how Bootstrap does it's thing and not fight the framework...
